### ISSUE TITLE
Publish on Flathub

### ISSUE THREAD

**Issue by JakobDev** [Rosalie241/RMG#26]
Would be relay nice, if you could publish RMG on [Flathub](https://flathub.org). Flathub is used by many Linux distros as source for Flatpaks, so the Users will be able to install RMG with 1 click. I have some experience in building a Flatpak, so I can help. I already noticed #5, but Flathub requires building without Internet. There are 2 things needed at the moment:

1. RMG can't store files in the same folder as the Binary, since Flatpaks are read only. They has to be saved in XDG_DATA_HOME/RMG or XDG_CONFIG_HOME/RMG.
2. git clone during the build is not allowed, because there's no Internet. I can include the needed Repo with commit and destination folder in the Manifest. The build script needs to check if the folder is already there and then not clone.

**Comment by JakobDev** [comment]
You don't need a mono repo. The 3rdParty  party stuff will still be downloaded with git. The only difference is, that flathub-builder is the one, wo will do the git clone, not your buildscript. I can tell flatpak-builder to do a git clone into a specific directory. It looks like this:
```yaml
type: git
url: https://github.com/mupen64plus/mupen64plus-core.git
commit: 57828d930280554c7400bb2bcf1e46c7f2ee8373
dest: Source/3rdParty/mupen64plus-core
```
You only need to edit your build script, so it will recognize that the git repos are alredy cloned, so it will not run git clone in that case.

**Comment by Rosalie241** [comment]
I took a look at the crash and fixed it, I've also revised the flatpak file:

```yml
app-id: com.github.Rosalie241.RMG
runtime: org.kde.Platform
runtime-version: "5.15-21.08"
sdk: org.kde.Sdk
command: RMG
finish-args:
  - --socket=x11
  - --share=ipc
  - --device=dri
  - --filesystem=host

modules:
  - minizip.json

  - name: hidapi
    sources:
      - type: archive
        url: https://github.com/libusb/hidapi/archive/refs/tags/hidapi-0.11.2.tar.gz
        sha256: bc4ac0f32a6b21ef96258a7554c116152e2272dacdec1e4620fc44abeea50c27
    modules:
      - name: libusb
        sources:
          - type: archive
            url: https://github.com/libusb/libusb/archive/refs/tags/v1.0.24.tar.gz
            sha256: b7724c272dfc5713dce88ff717efd60f021ca5b7c8e30f08ebb2c42d2eea08ae

  - name: RMG
    buildsystem: cmake
    config-opts:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DPORTABLE_INSTALL=OFF"
      - "-DNO_GIT_CLONE=ON"
    sources:
      - type: git
        url: https://github.com/Rosalie241/RMG.git
        commit: bcd84abb3a7714a7c8fb5f8ea9e7e9237861f1f7

      - type: git
        url: https://github.com/mupen64plus/mupen64plus-core.git
        commit: 57828d930280554c7400bb2bcf1e46c7f2ee8373
        dest: Source/3rdParty/mupen64plus-core

      - type: git
        url: https://github.com/mupen64plus/mupen64plus-rsp-hle.git
        commit: 88093cb43499eff53d343653cddcae2132af17ef
        dest: Source/3rdParty/mupen64plus-rsp-hle

      - type: git
        url: https://github.com/loganmc10/parallel-rsp.git
        commit: a9646b27c2ef399e5917735b4d84ebe93edcce39
        dest: Source/3rdParty/mupen64plus-rsp-parallel

      - type: git
        url: https://github.com/Rosalie241/mupen64plus-input-qt.git
        commit: e6cacb7fe6513cac4b30f7171d8ca7d1cd5fdb81
        dest: Source/3rdParty/mupen64plus-input-qt

      - type: git
        url: https://github.com/raphnet/mupen64plus-input-raphnetraw.git
        commit: 86112413e98a8648edb11d199673cc24d5799af8
        dest: Source/3rdParty/mupen64plus-input-raphnetraw

      - type: git
        url: https://github.com/amatho/mupen64plus-input-gca.git
        commit: d440611d3639fa974c7d52bd0ed2079d16428d5e
        dest: Source/3rdParty/mupen64plus-input-gca

      - type: git
        url: https://github.com/gonetz/GLideN64.git
        commit: 8343fd05c9a01ce2d73f7e32bb8355036759a05b
        dest: Source/3rdParty/mupen64plus-video-GLideN64

      - type: git
        url: https://github.com/loganmc10/parallel-rdp-standalone.git
        commit: 2efeaf014bad03ec26e081c22d8ca3566003b1ea
        dest: Source/3rdParty/mupen64plus-video-parallel
```

There are 3 problems remaining which I'm not sure how to fix:

1) RMG-Audio fails to initialize SDL (`SDL_Init(SDL_INIT_AUDIO)` returns `-1`)
![image](https://user-images.githubusercontent.com/18737914/149671606-12d95b9a-0395-47f7-a667-2e6eb2d8a744.png)

2) RMG is unable to open any ROM files
![image](https://user-images.githubusercontent.com/18737914/149671580-9168bae9-6602-4791-81e4-d40d5d45d0fc.png)

3) RMG is unable to select any directory (File -> Choose ROM Directory...)
